### ISSUE TITLE
unable to open SPI bus /dev/spidev2.1: No such file or directory & IMU Errors (MPU-9250)

### ISSUE THREAD

**Issue by safinwb** [juvinski/BBBMINI_V2#1]
I have updated the uEnv.txt

Not sure what i am missing out:
When I list the SPI devices using `ls /dev/spidev*`:

`/dev/spidev0.0  /dev/spidev1.0  /dev/spidev1.1`

When I run Ardurover:
```
Init ArduRover V4.2.0-rc4 (8ee85bdb)

Free RAM: 262144
SPI: unable to open SPI bus /dev/spidev2.1: No such file or directory
```
My uEnv.txt file:

```
#Docs: http://elinux.org/Beagleboard:U-boot_partitioning_layout_2.0

uname_r=5.10.109-bone-rt-r63
#uuid=
dtb=am335x-boneblack-bbbmini.dtb

###U-Boot Overlays###
###Documentation: http://elinux.org/Beagleboard:BeagleBoneBlack_Debian#U-Boot_Overlays
###Master Enable
#enable_uboot_overlays=1
###
###Overide capes with eeprom
#uboot_overlay_addr0=<file0>.dtbo
#uboot_overlay_addr1=<file1>.dtbo
#uboot_overlay_addr2=<file2>.dtbo
#uboot_overlay_addr3=<file3>.dtbo
###
###Additional custom capes
#uboot_overlay_addr4=<file4>.dtbo
#uboot_overlay_addr5=<file5>.dtbo
#uboot_overlay_addr6=<file6>.dtbo
#uboot_overlay_addr7=<file7>.dtbo
###
###Custom Cape
#dtb_overlay=<file8>.dtbo
###
###Disable auto loading of virtual capes (emmc/video/wireless/adc)
#disable_uboot_overlay_emmc=1
#disable_uboot_overlay_video=1
#disable_uboot_overlay_audio=1
#disable_uboot_overlay_wireless=1
#disable_uboot_overlay_adc=1
###
###PRUSS OPTIONS
###pru_rproc (4.14.x-ti kernel)
#uboot_overlay_pru=AM335X-PRU-RPROC-4-14-TI-00A0.dtbo
###pru_rproc (4.19.x-ti kernel)
#uboot_overlay_pru=AM335X-PRU-RPROC-4-19-TI-00A0.dtbo
###pru_uio (4.14.x-ti, 4.19.x-ti & mainline/bone kernel)
uboot_overlay_pru=AM335X-PRU-UIO-00A0.dtbo
###
###Cape Universal Enable
#enable_uboot_cape_universal=1
###
###Debug: disable uboot autoload of Cape
#disable_uboot_overlay_addr0=1
#disable_uboot_overlay_addr1=1
#disable_uboot_overlay_addr2=1
#disable_uboot_overlay_addr3=1
###
###U-Boot fdt tweaks... (60000 = 384KB)
#uboot_fdt_buffer=0x60000
###U-Boot Overlays###

console=ttyS0,115200n8
cmdline=coherent_pool=1M net.ifnames=0 lpj=1990656 rng_core.default_quality=100 quiet

#In the event of edid real failures, uncomment this next line:
#cmdline=coherent_pool=1M net.ifnames=0 lpj=1990656 rng_core.default_quality=100 quiet video=HDMI-A-1:1024x768@60e

#Use an overlayfs on top of a read-only root filesystem:
#cmdline=coherent_pool=1M net.ifnames=0 lpj=1990656 rng_core.default_quality=100 quiet overlayroot=tmpfs

##enable Generic eMMC Flasher:
#cmdline=init=/opt/scripts/tools/eMMC/init-eMMC-flasher-v3.sh
```

**Comment by juvinski** [comment]
Hi,

could you please run a
ls /dev/i2c*

to see if the ports is detected ?

**Comment by safinwb** [comment]
They are detected:
`
/dev/i2c-0  /dev/i2c-2
`

**Comment by safinwb** [comment]
I have attached boot messages:

Here is current:
[am355_env.txt](https://github.com/juvinski/BBBMINI_V2/files/8823515/am355_env.txt)

Here was my previous working one:
[old_env.txt](https://github.com/juvinski/BBBMINI_V2/files/8823516/old_env.txt)

**Comment by juvinski** [comment]
Hi @safinwb 

the dtb is ok once there is no i2c-1
I don’t know why - I asked a lot of times , this dtb instead generate the spidev 2 is generating 0 and 1.

there is two ways. You can change ardupilot code to use the spidev 0 and 1 or you can create a symlink for spidev 2 - sudo ln -s /dev/spidev1.0 /dev/spidev2.0 and sudo ln -s /dev/spidev1.1 /dev/spidev2.1

the symlimk must be created on every boot - you can create  rc.local script for that or on the ardupilot service file call a script to create this symlinks

**Comment by safinwb** [comment]
I will go the route of doing symlink, the only error I am getting now is
`
Config Error: Baro: unable to initialise driver
`

When I run MPU9250 test:
`
MPU 9250 Test
MPU9250: Onboard IMU detected
AK8963: Onboard compass detected
`

When I run ms5611_test:
`
MS5611 test
MS5611 detected successfully!
Pressure:100490.98 Temperature:40.01 Altitude:0.04 climb=0.25 t=15
Pressure:100492.79 Temperature:40.03 Altitude:-0.12 climb=1.45 t=14
Pressure:100493.03 Temperature:40.04 Altitude:-0.14 climb=2.48 t=13
`

**Comment by safinwb** [comment]
> I will go the route of doing symlink, the only error I am getting now is `Config Error: Baro: unable to initialise driver`
> 
> When I run MPU9250 test: `MPU 9250 Test MPU9250: Onboard IMU detected AK8963: Onboard compass detected`
> 
> When I run ms5611_test: `MS5611 test MS5611 detected successfully! Pressure:100490.98 Temperature:40.01 Altitude:0.04 climb=0.25 t=15 Pressure:100492.79 Temperature:40.03 Altitude:-0.12 climb=1.45 t=14 Pressure:100493.03 Temperature:40.04 Altitude:-0.14 climb=2.48 t=13`

Okay for this issue, I have to set SPI devices in my AP_HAL_LINUX setup in ardupilot code. I have things going crazy now, but atleast it is showing up on mission planner now.

Things going crazy: IMU/Compass acting wierd; will look more into it after the weekend.

`MPU: temp reset IMU[0] 8096 176
MPU: IMU[0] stop at 5 of 5
MPU: temp reset IMU[0] 8112 6624
MPU: IMU[0] stop at 4 of 4
MPU: temp reset IMU[0] 8160 2992
MPU: IMU[0] stop at 5 of 5
MPU: temp reset IMU[0] 8048 1248
MPU: IMU[0] stop at 14 of 14
MPU: temp reset IMU[0] 8096 -1120
MPU: IMU[0] stop at 5 of 5
MPU: temp reset IMU[0] 8112 3184
MPU: IMU[0] stop at 5 of 5
MPU: temp reset IMU[0] 8064 5296
MPU: IMU[0] stop at 8 of 8
MPU: temp reset IMU[0] 8128 4208
MPU: IMU[0] stop at 4 of 4
MPU: temp reset IMU[0] 8192 5024
MPU: IMU[0] stop at 24 of 36
MPU: temp reset IMU[0] 8128 432
MPU: IMU[0] stop at 2 of 2
MPU: temp reset IMU[0] 8128 -1761
MPU: IMU[0] stop at 3 of 3
`

**Comment by juvinski** [comment]
You need to disable the ins_fastrate in the parameters , without that you will have several imu errors

**Comment by safinwb** [comment]
yep, INS_FAST_SAMPLE is set to 0, but the IMU keeps resetting by EKF3

**Comment by juvinski** [comment]
If I not wrong, the 0 is enabled for imu 0 - https://ardupilot.org/copter/docs/parameters.html#ins-fast-sample-fast-sampling-mask

check the messages in mission planner to see if there is error or imu reset.

**Comment by safinwb** [comment]
When I set it to 1:
` IMU0: fast sampling enabled 8.0KHz/1.0Hz `

When I set it to 0: It doesn't show the fast sampling enable message.

Regardless: i get the same reset message when i run the binary.

In mission planner messages(with both INS_FAST_SAMPLE on and off):
![reset](https://user-images.githubusercontent.com/46702275/172018713-6e7cea9b-909c-4e93-be56-75f4e06a7719.png)

**Comment by juvinski** [comment]
That is the reason I updated to use the ICM20948 - with this IMU I never had problems.
In my board with mpu9250 I have 1 imu forces reset at every 5 or 10 minutes with fast sample disabled, with enabled I have several error messages.

**Comment by safinwb** [comment]
the wierd thing is I've never noticed this error with using this IMU till i put on 4.2, or maybe it was less frequent like you said that i haven't seen it. I'll try to see if it's something I'm missing in setting up the IMU to make this work.

Now looks like ICM-29948 is out of stock everywhere or super inflated prices, even out of stock build your own breakout 😅

**Comment by juvinski** [comment]
Hi @safinwb ,
I compared the codes since the 3.8 and I didn't see any change in the spi lower level functions - open, read and write, so I believe or is something in the linux kernel or something inside the EKF3 - the major difference between 3.x to 4.x version of ardupilot.
I tested with the icm and everything is working fine without any error.
I believe - once the mpu-9250 is EOL and there are several in the market what I believe there is no shortage problem, meanwhile I believe the ICM is facing this shortage problem because today price in aliexpress is around U$ 35, and in 2020 I paid around U$ 5 per unit.

**Comment by safinwb** [comment]
Yep you struck your luck with that $5 modules 😅

It's not the kernel problem as i ran my older code (which is mix and match of versions between 3.5-3.8), and it worked fine with MPU-9250 on this kernel. So it's definitely EK3. I'm going to try other stuff to see why this is happening.

**Comment by juvinski** [comment]
You can try to update again to the 5.10 and Ardupilot 4.2 and disable ekf3 and enable ekf2 to see what can happen.

**Comment by safinwb** [comment]
Okay it was a stupid mistake from my side:
`SPIDesc("mpu9250",    2, 1, SPI_MODE_0, 8, SPI_CS_KERNEL,  1*MHZ,  20*MHZ),`

I had changed it to 20*MHZ, i was doing that previously in my other firmwares, reverted it back to original.

FIxed so far. Going to test for other issues.

**Comment by safinwb** [comment]
Okat that was the root of all problems, even spidev, i think:

Because I set it 2,1 - 2,0 - 1,0; I was getting SPI error, and the speed. Had it to set it to whatever SPI was detecting 

    SPIDesc("mpu9250",    2, 1, SPI_MODE_0, 8, SPI_CS_KERNEL,  1*MHZ, 10*MHZ),
    SPIDesc("ms5611",     2, 0, SPI_MODE_0, 8, SPI_CS_KERNEL,  10*MHZ,10*MHZ),
    SPIDesc("ublox",      1, 0, SPI_MODE_0, 8, SPI_CS_KERNEL,  5*MHZ, 5*MHZ),
