### ISSUE TITLE
No PWM Output

### ISSUE THREAD

**Issue by safinwb** [juvinski/BBBMINI_V2#2]
Successfully tested other stuff out with the kernel, but today when i set my servos up - there is no pwm output, even with logic analyzer it shows low.

Anything I should be looking for ?

**Comment by safinwb** [comment]
Didn't notice the default pru was commented out:

`&pruss {
	pinctrl-names = "default";
	pinctrl-0 = <&pru_pins>;
	status = "okay";
};`

**Comment by juvinski** [comment]
How you was trying to use the servos ?
By default you should use the pru - output pins for that - once they use the PRU to generate the pwm pulses - ardupilot generate values on the shared memory and the pru reads this space and generate the pwm output on the channel.
Under ardupilot, on the SERVOX_Function you should set as servo if I not wrong - or on the mission planner there is a servo tab and you can set outputs as servo outputs and then use it.
